name: store_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_animate: ^4.5.2
  quick_actions: ^1.1.0
  widget_and_text_animator: ^1.1.5
  flutter_localization: ^0.3.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add your assets here
  assets:
    - assets/
    - lang/ar.json
    - lang/en.json

  # If you have custom fonts, uncomment and configure this section
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700